# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal function to load data for calculation.
#'
#' This function reads group/cluster membership and element
#' annotation datasets for analysis. It does not return anything,
#' it just create required structures in memory.
#'
#' !Note! This internal function is not for regular users.
#' Use \code{\link{run_enrichment}} for analysis.
#'
#'
#' @param x group/cluster membership data with element name in the
#' first column and group id in the second
#' @param anno1 first annotation dataset with term id, term name and
#' the element name in columns one, two and three respectively.
#' @param anno2 second annotation dataset.
NULL

test <- function() {
    invisible(.Call('_rEnrich_test', PACKAGE = 'rEnrich'))
}

#' Reset calculation environment.
#' @noRd
reset <- function() {
    invisible(.Call('_rEnrich_reset', PACKAGE = 'rEnrich'))
}

#' Clean up the calculation environment remove all results.
#' @noRd
erase <- function() {
    invisible(.Call('_rEnrich_erase', PACKAGE = 'rEnrich'))
}

#' Internal function to load each dataset
#'
#' This function flattens an inputted Rcpp::DataFrame object and 
#' returns a Rcpp::StringVector object. 
#'
#' !Note! This internal function is not for regular users.
#' Use \code{\link{run_enrichment}} for analysis.
#'
#' @param r_set an Rcpp::DataFrame containing either two or three columns
#'
fill_dataset <- function(r_set) {
    .Call('_rEnrich_fill_dataset', PACKAGE = 'rEnrich', r_set)
}

#'
load <- function(x = NULL, anno1 = NULL, anno2 = NULL) {
    invisible(.Call('_rEnrich_load', PACKAGE = 'rEnrich', x, anno1, anno2))
}

#' Internal function to run enrichment analysis.
#'
#' This function perform actual calculations.
#'
#' !Note! This internal function is not for regular users.
#' Use \code{\link{run_enrichment}} for analysis.
#'
#' @param useChi2 =0,
#' @param useOneSided =0,
#' @param useTwoSided =1,
#' @param runPerm =0,
#' @param singlePerm =0,
#' @param useSeed =0,
#' @param setNOP =0,
#' @param pesudoCount =-1.0,
#' @param FDRmeth ="BY"
#'
run <- function(useAnno = 0L, useChi2 = 0L, useOneSided = 0L, useTwoSided = 1L, useRelDist = 0L, runPerm = 0L, singlePerm = 0L, setNOP = 0L, pesudoCount = -1.0, useSeed = 0L, FDRmeth = "BY") {
    invisible(.Call('_rEnrich_run', PACKAGE = 'rEnrich', useAnno, useChi2, useOneSided, useTwoSided, useRelDist, runPerm, singlePerm, setNOP, pesudoCount, useSeed, FDRmeth))
}

#' Internal function to ggregate results into the final matrix.
#'
#' !Note! This internal function is not for regular users.
#' Use \code{\link{run_enrichment}} for analysis.
#'
#'
#' @param printTwoSided print two sided p-values
#' @param usePrintAlt print also alternative side, i.e. depletion
#' @param usePrintCnew print old community ids
#' @param usePrintID print annotation ID if \code{TRUE},
#' else annotation description
#' @param usePrintAn print annotation type size
#'
getResults <- function(printTwoSided = 1L, usePrintAlt = 0L, usePrintCnew = 0L, usePrintID = 0L, usePrintAn = 1L) {
    .Call('_rEnrich_getResults', PACKAGE = 'rEnrich', printTwoSided, usePrintAlt, usePrintCnew, usePrintID, usePrintAn)
}

