# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function() {
    invisible(.Call('_rEnrich_test', PACKAGE = 'rEnrich'))
}

#' Reset calculation environment.
#' @noRd
reset <- function() {
    invisible(.Call('_rEnrich_reset', PACKAGE = 'rEnrich'))
}

#' Clean up the calculation environment remove all results.
#' @noRd
erase <- function() {
    invisible(.Call('_rEnrich_erase', PACKAGE = 'rEnrich'))
}

#' Internal function to help load a sdataset
#'
#' This function flattens an R DataFrame object,  
#' returning an R StringVector object. 
#'
#' !Note! This internal function is not for regular users.
#' Use \code{\link{run_enrichment}} for analysis.
#'
#' @param r_set an Rcpp::DataFrame containing either two or three columns
#'
fill_dataset <- function(r_set) {
    .Call('_rEnrich_fill_dataset', PACKAGE = 'rEnrich', r_set)
}

#' Internal function to load data for calculation.
#'
#' This function reads group/cluster membership and element
#' annotation datasets for analysis. It does not return anything,
#' it just create required structures in memory.
#'
#' !Note! This internal function is not for regular users.
#' Use \code{\link{run_enrichment}} for analysis.
#'
#'
#' @param x group/cluster membership data with element name in the
#' first column and group id in the second
#' @param anno1 first annotation dataset with term id, term name and
#' the element name in columns one, two and three respectively.
#' @param anno2 is an optional second annotation dataset.
#' @param anno3 is an optional second annotation dataset.
#'
load <- function(x = NULL, anno1 = NULL, anno2 = NULL, anno3 = NULL) {
    invisible(.Call('_rEnrich_load', PACKAGE = 'rEnrich', x, anno1, anno2, anno3))
}

#' Internal function to run network cluster enrichment analysis over loaded annotation
#' datasets.
#'
#' This function perform actual calculations.
#'
#' !Note! This internal function is not for regular users.
#' Use \code{\link{run_enrichment}} for analysis.
#'
#' @param method="cluster", whether to perform network or cluster enrichmnet analysis over annotation datasets.
#' @param useAnno set the annotation dataset(s) to peform the cluster enrichment analysis.
#' Default is 0, i.e. first loaded annotation set.
#' @param useChi2 =0, boolean vlaue whether to calculate Chi2 p-values for cluster enrichemnt given two annotation sets.
#' @param useOneSided =0, boolean (default set to FALSE), if set true the test statistic is tested the area under one side of a distribution (hypergeometric, chi2).
#' @param useTwoSided =1, boolean (default set to TRUE), if set true the test statistic is tested the area under both sides of a distribution (hypergeometric, chi2).
#' @param useRelDist =0, boolean value whether to calcuate the probability of the intersection distance for cluster enrichemnt given two annotation sets //' given by eqn (13) pg 8 (A. T. Kalinka 2014).
#' @param runPerm =0, boolean value whether to preform a permutation study for cluster enrichemnt given one annotation set.
#' @param singlePerm =0,
#' @param setNOP =0, integer value to set the number pertuations (default is 1000) if preforming a permutation study for cluster enrichemnt
#' given one annotation set.
#' @param pesudoCount =-1.0, non zero value to avoid p-values of zero in the permutation test.
#' @param FDRmeth ="BY", select the False Discovery Rate method to use. Choice of Benjamini and Hochberg FDR (BH), Benjamini and Liu FDR (BL), or Benjamini and Yekutieli FDR (BY). Default set to (BY).
#' @param useSeed =0 set the random number seed if preforming a permutation study for cluster enrichemnt given one annotation set.
#'
run <- function(method = "cluster", useAnno = 0L, useChi2 = 0L, useOneSided = 0L, useTwoSided = 1L, useRelDist = 0L, runPerm = 0L, singlePerm = 0L, setNOP = 0L, pesudoCount = -1.0, useSeed = 0L, FDRmeth = "BY") {
    invisible(.Call('_rEnrich_run', PACKAGE = 'rEnrich', method, useAnno, useChi2, useOneSided, useTwoSided, useRelDist, runPerm, singlePerm, setNOP, pesudoCount, useSeed, FDRmeth))
}

#' Internal function to ggregate results into the final matrix.
#'
#' !Note! This internal function is not for regular users.
#' Use \code{\link{run_enrichment}} for analysis.
#'
#'
#' @param printTwoSided print two sided p-values
#' @param usePrintAlt print also alternative side, i.e. depletion
#' @param usePrintCnew print old community ids
#' @param usePrintID print annotation ID if \code{TRUE},
#' else annotation description
#' @param usePrintAn print annotation type size
#'
getResults <- function(printTwoSided = 1L, usePrintAlt = 0L, usePrintCnew = 0L, usePrintID = 0L, usePrintAn = 1L) {
    .Call('_rEnrich_getResults', PACKAGE = 'rEnrich', printTwoSided, usePrintAlt, usePrintCnew, usePrintID, usePrintAn)
}

